Add Quilt support
RPMTW/RPMTW-Platform-Mod pull request #155
Opened 2022-07-03 14:05 UTC by BennyDioxide

加入了Quilt的支援。
可惜Dependancy會一直壞掉。

2022-07-03 15:36 UTC, BennyDioxide commented
現在可以用了，但是Mod Menu不支援1.19的Quilt

2022-07-04 02:16 UTC, SiongSng requested changes

2022-07-04 02:16 UTC, SiongSng commented on gradle.properties
> +qsl_version=2.0.0-beta.9
沒看到有其他地方使用 `qsl_version` 這參數

2022-07-04 02:18 UTC, SiongSng requested changes

2022-07-04 02:18 UTC, SiongSng commented on common/src/main/kotlin/com/rpmtw/rpmtw_platform_mod/RPMTWPlatformModPlugin.kt
> +    fun getResourcePacksFolder(): File { throw AssertionError() }
或許實作成 `getGameDirectory` 這類的會更好，擴充性更佳

2022-07-04 11:26 UTC, BennyDioxide commented on common/src/main/kotlin/com/rpmtw/rpmtw_platform_mod/RPMTWPlatformModPlugin.kt
> +    fun getResourcePacksFolder(): File { throw AssertionError() }
我一開始也有這麼想，但還是謝謝你的建議！

2022-07-05 14:20 UTC, SiongSng requested changes

2022-07-05 14:20 UTC, SiongSng commented on quilt/src/main/kotlin/com/rpmtw/rpmtw_platform_mod/quilt/RPMTWPlatformModQuilt.kt
> +
```suggestion
```
多出一行空白

2022-07-05 14:20 UTC, SiongSng commented on quilt/src/main/resources/rpmtw_platform_mod.accesswidener
> +accessWidener	v1	named
這個檔案是執行時才產生的，所以要排除在外，不要上傳到 git

2022-07-06 15:01 UTC, BennyDioxide commented
能做的都做完了!

2022-07-07 06:15 UTC, BennyDioxide commented
> 能做的都做完了!

噢不
Quilt Kotlin Library 還沒解決…

2022-08-07 13:35 UTC, SiongSng commented
Quilt Kotlin Library 不知道什麼時候才出正式版

2022-08-12 08:45 UTC, SiongSng commented
https://github.com/QuiltMC/quilt-kotlin-libraries 感覺短時間內都不會有正式版

2022-08-12 08:45 UTC, SiongSng commented
現在這個分支跟 `main` 差異越來越大了 之後要修衝突比較麻煩.w.

2022-08-24 08:59 UTC, BennyDioxide commented
Conflicts solved

2022-10-22 06:35 UTC, SiongSng commented
![image](https://user-images.githubusercontent.com/48402225/197324285-06d5a858-236b-4860-9567-d3b5d3979131.png)
看來距離 QKL 1.0.0 還有一段時間

2022-10-23 02:09 UTC, SiongSng commented
#179 若宇宙通訊 4.0 合併後可能會碰到一點小衝突
因為我有修改了 fabric 的 mixin 設定檔

2022-10-26 15:00 UTC, SiongSng commented
可能要麻煩您解一下衝突

2022-11-03 15:01 UTC, SiongSng commented
我在想有沒有什麼方式直接不靠 QKL 就可以正常運作
不然 QKL 不知道要等到何時XD

2022-11-03 15:05 UTC, SiongSng requested changes

2022-11-03 16:09 UTC, BennyDioxide commented
> 我在想有沒有什麼方式直接不靠 QKL 就可以正常運作
> 不然 QKL 不知道要等到何時XD

可以啊
自己包Kotlin runtime 進去
但會很肥

2022-11-14 14:46 UTC, BennyDioxide commented
好耶
把QKL換Fabric Language Kotlin後就可以正常用了
但和原本fabric版的差別只在用QSL代替Fabric API
還有Quilt會把它當Quilt mod而不是Fabric mod
連前置模組都一模一樣

2022-11-18 09:07 UTC, SiongSng commented
@BennyDioxide 我猜會有這錯誤應該是 Quilt 上的 accesswidener 沒設定好

2022-11-18 09:08 UTC, SiongSng commented
這是 Fabric 的做法

```kts
val accessWidenerFile = project(":common").file("src/main/resources/rpmtw_platform_mod.accesswidener")

loom {
    accessWidenerPath.set(accessWidenerFile)
}

tasks {
    val resourcesPath = file("src/main/resources")
    // The access widener file is needed in :fabric project resources when the game is run.
    val copyAccessWidener by registering(Copy::class) {
        from(accessWidenerFile)
        into(resourcesPath)
    }

    processResources {
        dependsOn(copyAccessWidener)
        inputs.property("version", project.version)

        filesMatching("fabric.mod.json") {
            expand("version" to project.version)
        }
    }

    sourcesJar {
        val commonSources = project(":common").tasks.sourcesJar
        dependsOn(commonSources)
        from(commonSources.get().archiveFile.map { zipTree(it) })
        exclude("rpmtw_platform_mod.accesswidener")
    }
}
```

2022-11-18 09:09 UTC, SiongSng requested changes

2022-11-18 09:09 UTC, SiongSng commented on quilt/src/main/kotlin/com/rpmtw/rpmtw_platform_mod/fabric/RPMTWPlatformModPluginImpl.kt
> +    fun registerClientCommand(
@BennyDioxide 你還是忘了刪除XD

2022-11-20 06:49 UTC, SiongSng approved these changes
LGTM

2022-11-20 07:04 UTC, merged